### ISSUE TITLE
Caesar cipher

### ISSUE THREAD

**Issue by thsaravana** [divyap7/JavaPlayground#6]
Given any word, encode it via Caesar's cipher.

i.e, ABCDEF -> DEFGHI
(increment each character by 3)

**Comment by thsaravana** [comment]
Nope. This is not completed. There is a bug.
XYZ -> ABC
but
XYZ -> [\]

**Comment by thsaravana** [comment]
You used `StringBuffer`, why not `StringBuilder`? What is the difference between the two?

**Comment by divyap7** [comment]
Both share same functions but String builder is faster coz its not thread safe.
